export const tr = {
  giris: 'Giriş',
  kayit: 'Kayıt Ol',
  sifremiUnuttum: 'Şifremi Unuttum',
  anaSayfa: 'Ana Sayfa',
  bugunkuPlan: 'Bugünkü Egzersiz Planım',
  egzersizDetay: 'Egzersiz Detayı',
  kameraTakip: 'Kamera ile Egzersiz Takibi',
  ilerleme: 'İlerleme',
  agriGunlugu: 'Ağrı ve Durum Günlüğü',
  bildirimler: 'Bildirimler',
  profilAyarlar: 'Profil ve Ayarlar',
  erisilebilirlik: 'Erişilebilirlik Ayarları',
  hosGeldiniz: 'Bugün kendin için harika bir gün!',
  basla: 'Başla',
  tamamla: 'Tamamla',
  geri: 'Geri',
  kaydet: 'Kaydet',
  geriBildirimOrnek: 'Dizinizi biraz daha bükün.',
};
